apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "spiffe-csi-driver.fullname" . }}
  namespace: {{ template "spiffe-csi-driver.namespace" . }}
  labels:
    app: {{ template "spiffe-csi-driver.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "spiffe-csi-driver.name" . }}
  template:
    metadata:
      namespace: {{ template "spiffe-csi-driver.namespace" . }}
      labels:
        app: {{ template "spiffe-csi-driver.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        # This is the container which runs the SPIFFE CSI driver.
        - name: {{ template "spiffe-csi-driver.name" . }}
          image: {{ .Values.images.csiDriver.image }}
          imagePullPolicy: {{ .Values.images.csiDriver.imagePullPolicy }}
          args: [
            "-workload-api-socket-dir", "/spire-agent-socket",
            "-csi-socket-path", "/spiffe-csi/csi.sock",
          ]
          env:
            # The CSI driver needs a unique node ID. The node name can be
            # used for this purpose.
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            # The volume containing the SPIRE agent socket. The SPIFFE CSI
            # driver will mount this directory into containers.
            - mountPath: /spire-agent-socket
              name: spire-agent-socket-dir
              readOnly: true
            # The volume that will contain the CSI driver socket shared
            # with the kubelet and the driver registrar.
            - mountPath: /spiffe-csi
              name: spiffe-csi-socket-dir
            # The volume containing mount points for containers.
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
          securityContext:
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            capabilities:
              drop:
                - ALL
            privileged: {{ .Values.securityContext.privileged }}
        # This container runs the CSI Node Driver Registrar which takes care
        # of all the little details required to register a CSI driver with
        # the kubelet.
        - name: node-driver-registrar
          image: {{ .Values.images.k8sRegistrar.image }}
          imagePullPolicy: {{ .Values.images.k8sRegistrar.imagePullPolicy }}
          args: [
            "-csi-address", "/spiffe-csi/csi.sock",
            "-kubelet-registration-path", "/var/lib/kubelet/plugins/csi.spiffe.io/csi.sock",
          ]
          volumeMounts:
            # The registrar needs access to the SPIFFE CSI driver socket
            - mountPath: /spiffe-csi
              name: spiffe-csi-socket-dir
            # The registrar needs access to the Kubelet plugin registration
            # directory
            - name: kubelet-plugin-registration-dir
              mountPath: /registration
      volumes:
        # This volume is used to share the workload api socket between the
        # CSI driver and SPIRE agent
        - name: spire-agent-socket-dir
          hostPath:
            path: /run/spire/socket-dir
            type: DirectoryOrCreate
        # This volume is where the socket for kubelet->driver communication lives
        - name: spiffe-csi-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.spiffe.io
            type: DirectoryOrCreate
        # This volume is where the SPIFFE CSI driver mounts volumes
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        # This volume is where the node-driver-registrar registers the plugin
        # with kubelet
        - name: kubelet-plugin-registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: "csi.spiffe.io"
spec:
  # We only support ephemeral, inline volumes. We don't need a controller to
  # provision and attach volumes.
  attachRequired: false

  # We want the pod information so that the CSI driver can verify that an
  # ephemeral mount was requested.
  podInfoOnMount: true

  # We don't want (or need) K8s to change ownership on the contents of the mount
  # when it is moutned into the pod, since the Workload API is completely open
  # (i.e. 0777).
  # Note, this was added in Kubernetes 1.19, so omit
  fsGroupPolicy: None

  # We only support ephemeral volumes. Note that this requires Kubernetes 1.16
  volumeLifecycleModes: # added in Kubernetes 1.16, this field is beta
    - Ephemeral
---
