# Required cluster role to allow spire-server to query k8s API server
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ template "spire-server.fullname" . }}-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - get
      - create
---
# Role for the SPIRE server
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "spire-server.fullname" . }}-role
  namespace: {{ template "spire-server.namespace" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  {{ if .Values.spireServer.config.plugins.k8sbundleNotifier.enabled }}
  - apiGroups:
      - ""
    resourceNames:
      - {{ .Values.spireServer.config.plugins.k8sbundleNotifier.configMap }}
    resources:
      - configmaps
    verbs:
      - get
      - patch
  {{ end }}
---
