# Binds spire-agent cluster role to spire-agent service account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  {{ template "spire-agent.fullname" . }}-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount }}
    namespace: {{ template "spire-agent.namespace" . }}
roleRef:
  kind: ClusterRole
  name:  {{ template "spire-agent.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
